Entropy Pool + `get_random`
Ashet-Technologies/Ashet-OS pull request #11
Opened 2024-07-16 06:44 UTC by Rexicon226

2024-07-16 10:07 UTC, ikskuh requested changes

2024-07-16 10:07 UTC, ikskuh commented on src/abi/abi.zig
> +    pub extern fn @"ashet.random.get_random"([*]u8, usize) void;
Can you also add the function to `abi-v2.zig` in a proper subnamespace `random`, where both an `iop` and `syscall` are implemented?
Name them `extern "syscall" fn get_soft_random(...) void` and `extern "iop" fn get_strict_random(...) error{}!void`"

Also add documentation to the syscalls in `abi-v2.zig`

2024-07-16 10:07 UTC, ikskuh commented on src/kernel/port/platform/x86.zig
> +pub fn get_clock() u64 {
```zig
/// Invokes x86 Read Time-Stamp Counter instruction
pub fn rdtsc() u64
```
and call this from another function that abstracts the instruction name into a general concept. `get_clock` is too broad to be a good name (timer clock? wall clock? monotonic clock?)

maybe use `get_cpu_cycle_counter()` or something like that

2024-07-16 10:07 UTC, ikskuh commented on src/kernel/port/platform/x86.zig
> +pub fn get_rdseed() ?u64 {
Same here, wrap this into another function called `get_cpu_random_seed()` or similar

2024-07-16 10:07 UTC, ikskuh commented on src/kernel/components/random.zig
> +    const clock = get_hw_entropy();
maybe cpu id, risc-v status regs, ... here as well?

2024-07-17 00:42 UTC, Rexicon226 commented on src/kernel/port/platform/x86.zig
> +pub fn get_clock() u64 {
Agreed on the `get_cpu_cycle_counter`.

2024-07-25 16:06 UTC, merged